indignissimos/config/routes.rb
Rails.application.routes.draw do
  resources :alunoprofessors
  resources :escolas
  resources :professores
  resources :alunos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

indignissimos/app/models/alunoprofessor.rb
class Alunoprofessor < ApplicationRecord
    
    belongs_to :aluno
    belongs_to :professore
    
end

indignissimos/app/controllers/alunoprofessors_controller.rb
class AlunoprofessorsController < ApplicationController
  before_action :set_alunoprofessor, only: [:show, :edit, :update, :destroy]

  # GET /alunoprofessors
  # GET /alunoprofessors.json
  def index
    @alunoprofessors = Alunoprofessor.all
  end

  # GET /alunoprofessors/1
  # GET /alunoprofessors/1.json
  def show
  end

  # GET /alunoprofessors/new
  def new
    @alunoprofessor = Alunoprofessor.new
  end

  # GET /alunoprofessors/1/edit
  def edit
  end

  # POST /alunoprofessors
  # POST /alunoprofessors.json
  def create
    @alunoprofessor = Alunoprofessor.new(alunoprofessor_params)

    respond_to do |format|
      if @alunoprofessor.save
        format.html { redirect_to @alunoprofessor, notice: 'Alunoprofessor was successfully created.' }
        format.json { render :show, status: :created, location: @alunoprofessor }
      else
        format.html { render :new }
        format.json { render json: @alunoprofessor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alunoprofessors/1
  # PATCH/PUT /alunoprofessors/1.json
  def update
    respond_to do |format|
      if @alunoprofessor.update(alunoprofessor_params)
        format.html { redirect_to @alunoprofessor, notice: 'Alunoprofessor was successfully updated.' }
        format.json { render :show, status: :ok, location: @alunoprofessor }
      else
        format.html { render :edit }
        format.json { render json: @alunoprofessor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alunoprofessors/1
  # DELETE /alunoprofessors/1.json
  def destroy
    @alunoprofessor.destroy
    respond_to do |format|
      format.html { redirect_to alunoprofessors_url, notice: 'Alunoprofessor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alunoprofessor
      @alunoprofessor = Alunoprofessor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alunoprofessor_params
      params.require(:alunoprofessor).permit(:aluno_id, :professor_id)
    end
end

indignissimos/app/helpers/alunoprofessors_helper.rb
module AlunoprofessorsHelper
end

indignissimos/app/views/alunoprofessors/_form.html.erb
<%= form_for(alunoprofessor) do |f| %>
  <% if alunoprofessor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(alunoprofessor.errors.count, "error") %> prohibited this alunoprofessor from being saved:</h2>

      <ul>
      <% alunoprofessor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :aluno_id %>
    <%= f.text_field :aluno_id %>
  </div>

  <div class="field">
    <%= f.label :professor_id %>
    <%= f.text_field :professor_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

indignissimos/app/views/alunoprofessors/edit.html.erb
<h1>Editing Alunoprofessor</h1>

<%= render 'form', alunoprofessor: @alunoprofessor %>

<%= link_to 'Show', @alunoprofessor %> |
<%= link_to 'Back', alunoprofessors_path %>

indignissimos/app/views/alunoprofessors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alunoprofessors</h1>

<table>
  <thead>
    <tr>
      <th>Aluno</th>
      <th>Professor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alunoprofessors.each do |alunoprofessor| %>
      <tr>
        <td><%= alunoprofessor.aluno_id %></td>
        <td><%= alunoprofessor.professor_id %></td>
        <td><%= link_to 'Show', alunoprofessor %></td>
        <td><%= link_to 'Edit', edit_alunoprofessor_path(alunoprofessor) %></td>
        <td><%= link_to 'Destroy', alunoprofessor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alunoprofessor', new_alunoprofessor_path %>

indignissimos/app/views/alunoprofessors/new.html.erb
<h1>New Alunoprofessor</h1>

<%= render 'form', alunoprofessor: @alunoprofessor %>

<%= link_to 'Back', alunoprofessors_path %>

indignissimos/app/views/alunoprofessors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Aluno:</strong>
  <%= @alunoprofessor.aluno_id %>
</p>

<p>
  <strong>Professor:</strong>
  <%= @alunoprofessor.professor_id %>
</p>

<%= link_to 'Edit', edit_alunoprofessor_path(@alunoprofessor) %> |
<%= link_to 'Back', alunoprofessors_path %>