indignissimos/config/routes.rb
Rails.application.routes.draw do
  resources :alunoprofessors
  resources :escolas
  resources :professores
  resources :alunos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

indignissimos/app/models/professore.rb
class Professore < ApplicationRecord
    belongs_to :escola
    
    has_many :alunos, through: :alunoprofessors
    has_many :alunoprofessors
end

indignissimos/app/controllers/professores_controller.rb
class ProfessoresController < ApplicationController
  before_action :set_professore, only: [:show, :edit, :update, :destroy]

  # GET /professores
  # GET /professores.json
  def index
    @professores = Professore.all
  end

  # GET /professores/1
  # GET /professores/1.json
  def show
    @alunoprofessors = Alunoprofessor.all
    @alunos = Aluno.all
  end

  # GET /professores/new
  def new
    @professore = Professore.new
  end

  # GET /professores/1/edit
  def edit
  end

  # POST /professores
  # POST /professores.json
  def create
    @professore = Professore.new(professore_params)

    respond_to do |format|
      if @professore.save
        format.html { redirect_to @professore, notice: 'Professore was successfully created.' }
        format.json { render :show, status: :created, location: @professore }
      else
        format.html { render :new }
        format.json { render json: @professore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /professores/1
  # PATCH/PUT /professores/1.json
  def update
    respond_to do |format|
      if @professore.update(professore_params)
        format.html { redirect_to @professore, notice: 'Professore was successfully updated.' }
        format.json { render :show, status: :ok, location: @professore }
      else
        format.html { render :edit }
        format.json { render json: @professore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professores/1
  # DELETE /professores/1.json
  def destroy
    @professore.destroy
    respond_to do |format|
      format.html { redirect_to professores_url, notice: 'Professore was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_professore
      @professore = Professore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def professore_params
      params.require(:professore).permit(:nome, :sobre, :idade, :salario, :escola_id)
    end
end

indignissimos/app/helpers/professores_helper.rb
module ProfessoresHelper
end

indignissimos/app/views/professores/_form.html.erb
<%= form_for(professore) do |f| %>
  <% if professore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(professore.errors.count, "error") %> prohibited this professore from being saved:</h2>

      <ul>
      <% professore.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %>
    <%= f.text_field :nome %>
  </div>

  <div class="field">
    <%= f.label :sobre %>
    <%= f.text_area :sobre %>
  </div>

  <div class="field">
    <%= f.label :idade %>
    <%= f.number_field :idade %>
  </div>

  <div class="field">
    <%= f.label :salario %>
    <%= f.text_field :salario %>
  </div>

<div class="field">
    <%= f.label :escola_id %>
    <%= f.number_field :escola_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

indignissimos/app/views/professores/edit.html.erb
<h1>Editing Professore</h1>

<%= render 'form', professore: @professore %>

<%= link_to 'Show', @professore %> |
<%= link_to 'Back', professores_path %>

indignissimos/app/views/professores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Professores</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Nome</th>
      <th>Escola</th>
      <th>Sobre</th>
      <th>Idade</th>
      <th>Salario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @professores.each do |professore| %>
      <tr>
        <td><%= professore.id %></td>
        <td><%= professore.nome %></td>
        <td><%= professore.escola.nome %></td>
        <td><%= professore.sobre %></td>
        <td><%= professore.idade %></td>
        <td><%= professore.salario %></td>
        <td><%= link_to 'Show', professore %></td>
        <td><%= link_to 'Edit', edit_professore_path(professore) %></td>
        <td><%= link_to 'Destroy', professore, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Professore', new_professore_path %>

indignissimos/app/views/professores/new.html.erb
<h1>New Professore</h1>

<%= render 'form', professore: @professore %>

<%= link_to 'Back', professores_path %>

indignissimos/app/views/professores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @professore.nome %>
</p>

<p>
  <strong>Sobre:</strong>
  <%= @professore.sobre %>
</p>

<p>
  <strong>Idade:</strong>
  <%= @professore.idade %>
</p>

<p>
  <strong>Salario:</strong>
  <%= @professore.salario %>
</p>

<%= link_to 'Edit', edit_professore_path(@professore) %> |
<%= link_to 'Back', professores_path %>