indignissimos/config/routes.rb
Rails.application.routes.draw do
  resources :alunoprofessors
  resources :escolas
  resources :professores
  resources :alunos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

indignissimos/app/models/escola.rb
class Escola < ApplicationRecord
        has_many :alunos
        has_many :professores
end

indignissimos/app/controllers/escolas_controller.rb
class EscolasController < ApplicationController
  before_action :set_escola, only: [:show, :edit, :update, :destroy]

  # GET /escolas
  # GET /escolas.json
  def index
    @escolas = Escola.all
  end

  # GET /escolas/1
  # GET /escolas/1.json
  def show
  end

  # GET /escolas/new
  def new
    @escola = Escola.new
  end

  # GET /escolas/1/edit
  def edit
  end

  # POST /escolas
  # POST /escolas.json
  def create
    @escola = Escola.new(escola_params)

    respond_to do |format|
      if @escola.save
        format.html { redirect_to @escola, notice: 'Escola was successfully created.' }
        format.json { render :show, status: :created, location: @escola }
      else
        format.html { render :new }
        format.json { render json: @escola.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /escolas/1
  # PATCH/PUT /escolas/1.json
  def update
    respond_to do |format|
      if @escola.update(escola_params)
        format.html { redirect_to @escola, notice: 'Escola was successfully updated.' }
        format.json { render :show, status: :ok, location: @escola }
      else
        format.html { render :edit }
        format.json { render json: @escola.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /escolas/1
  # DELETE /escolas/1.json
  def destroy
    @escola.destroy
    respond_to do |format|
      format.html { redirect_to escolas_url, notice: 'Escola was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_escola
      @escola = Escola.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def escola_params
      params.require(:escola).permit(:nome, :sobre)
    end
end

indignissimos/app/helpers/escolas_helper.rb
module EscolasHelper
end

indignissimos/app/views/escolas/_form.html.erb
<%= form_for(escola) do |f| %>
  <% if escola.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(escola.errors.count, "error") %> prohibited this escola from being saved:</h2>

      <ul>
      <% escola.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %>
    <%= f.text_field :nome %>
  </div>

  <div class="field">
    <%= f.label :sobre %>
    <%= f.text_area :sobre %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

indignissimos/app/views/escolas/edit.html.erb
<h1>Editing Escola</h1>

<%= render 'form', escola: @escola %>

<%= link_to 'Show', @escola %> |
<%= link_to 'Back', escolas_path %>

indignissimos/app/views/escolas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Escolas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Sobre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @escolas.each do |escola| %>
      <tr>
        <td><%= escola.nome %></td>
        <td><%= escola.sobre %></td>
        <td><%= link_to 'Show', escola %></td>
        <td><%= link_to 'Edit', edit_escola_path(escola) %></td>
        <td><%= link_to 'Destroy', escola, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Escola', new_escola_path %>

indignissimos/app/views/escolas/new.html.erb
<h1>New Escola</h1>

<%= render 'form', escola: @escola %>

<%= link_to 'Back', escolas_path %>

indignissimos/app/views/escolas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @escola.nome %>
</p>

<p>
  <strong>Sobre:</strong>
  <%= @escola.sobre %>
</p>

<%= link_to 'Edit', edit_escola_path(@escola) %> |
<%= link_to 'Back', escolas_path %>