indignissimos/config/routes.rb
Rails.application.routes.draw do
  resources :alunoprofessors
  resources :escolas
  resources :professores
  resources :alunos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

indignissimos/app/models/aluno.rb
class Aluno < ApplicationRecord
    belongs_to :escola
    
    has_many :professores, through: :alunoprofessors
    has_many :alunoprofessors
end

indignissimos/app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  before_action :set_aluno, only: [:show, :edit, :update, :destroy]

  # GET /alunos
  # GET /alunos.json
  def index
    @alunos = Aluno.all
  end

  # GET /alunos/1
  # GET /alunos/1.json
  def show
    @professores = Professore.all
    @alunoprofessors = Alunoprofessor.all
  end

  # GET /alunos/new
  def new
    @aluno = Aluno.new
  end

  # GET /alunos/1/edit
  def edit
  end

  # POST /alunos
  # POST /alunos.json
  def create
    @aluno = Aluno.new(aluno_params)

    respond_to do |format|
      if @aluno.save
        format.html { redirect_to @aluno, notice: 'Aluno was successfully created.' }
        format.json { render :show, status: :created, location: @aluno }
      else
        format.html { render :new }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alunos/1
  # PATCH/PUT /alunos/1.json
  def update
    respond_to do |format|
      if @aluno.update(aluno_params)
        format.html { redirect_to @aluno, notice: 'Aluno was successfully updated.' }
        format.json { render :show, status: :ok, location: @aluno }
      else
        format.html { render :edit }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alunos/1
  # DELETE /alunos/1.json
  def destroy
    @aluno.destroy
    respond_to do |format|
      format.html { redirect_to alunos_url, notice: 'Aluno was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aluno
      @aluno = Aluno.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aluno_params
      params.require(:aluno).permit(:nome, :sobre, :idade, :nascimento, :escola_id)
    end
end

indignissimos/app/helpers/alunos_helper.rb
module AlunosHelper
end

indignissimos/app/views/alunos/_form.html.erb
<%= form_for(aluno) do |f| %>
  <% if aluno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(aluno.errors.count, "error") %> prohibited this aluno from being saved:</h2>

      <ul>
      <% aluno.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %>
    <%= f.text_field :nome %>
  </div>

  <div class="field">
    <%= f.label :sobre %>
    <%= f.text_area :sobre %>
  </div>

  <div class="field">
    <%= f.label :idade %>
    <%= f.number_field :idade %>
  </div>

  <div class="field">
    <%= f.label :nascimento %>
    <%= f.datetime_select :nascimento %>
  </div>
  
  <div class="field">
    <%= f.label :escola_id %>
    <%= f.number_field :escola_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

indignissimos/app/views/alunos/edit.html.erb
<h1>Editing Aluno</h1>

<%= render 'form', aluno: @aluno %>

<%= link_to 'Show', @aluno %> |
<%= link_to 'Back', alunos_path %>

indignissimos/app/views/alunos/index.html.erb
<p id="notice"><%= notice %></p>
<h2><%= link_to 'Professores', professores_path %></h2>
<h1>Alunos</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Nome</th>
      <th>Escola</th>
      <th>Sobre</th>
      <th>Idade</th>
      <th>Nascimento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alunos.each do |aluno| %>
      <tr>
        <td><%= aluno.id %></td>
        <td><%= aluno.nome %></td>
        <td><%= aluno.escola.nome %></td>
        <td><%= aluno.sobre %></td>
        <td><%= aluno.idade %></td>
        <td><%= aluno.nascimento %></td>
        <td><%= link_to 'Show', aluno %></td>
        <td><%= link_to 'Edit', edit_aluno_path(aluno) %></td>
        <td><%= link_to 'Destroy', aluno, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Professores', professores_path %></td>
        </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Aluno', new_aluno_path %>

indignissimos/app/views/alunos/new.html.erb
<h1>New Aluno</h1>

<%= render 'form', aluno: @aluno %>

<%= link_to 'Back', alunos_path %>

indignissimos/app/views/alunos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @aluno.nome %>
</p>

<p>
  <strong>Sobre:</strong>
  <%= @aluno.sobre %>
</p>

<p>
  <strong>Idade:</strong>
  <%= @aluno.idade %>
</p>

<p>
  <strong>Nascimento:</strong>
  <%= @aluno.nascimento %>
</p>

<%= link_to 'Edit', edit_aluno_path(@aluno) %> |
<%= link_to 'Back', alunos_path %>

<!--<table>-->
<!--  <thead>-->
<!--    <tr>-->
<!--      <th>Nome</th>-->
<!--      <th>Comandos</th>-->
<!--    </tr>-->
<!--  </thead>-->

<!--  <tbody>-->
<!--    <% @aluno.professores.each do |professore| %>-->
<!--      <tr>-->
<!--        <td><%= professore.nome %></td>-->
<!--        <td><%= link_to 'Show', professore %></td>-->
<!--      </tr>-->
<!--    <% end %>-->
<!--  </tbody>-->
<!--</table>-->